# Render.yaml to deploy frontend + server as one Web Service
services:
  - type: web
    name: pizza-and-pasta
    env: node
    plan: starter
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm --prefix server start"
    healthCheckPath: "/healthz"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
